services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    command: npm run dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 8000:3000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli" ,"ping"]
      timeout: 20s
      interval: 10s
      retries: 10

volumes:
  db-data: